--- #YAML:1.0
name:                B-Lint-Pluggable
version:             1.0
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    B::Lint:                       1.09
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Joshua ben Jore <jjore@cpan.org>
